version: '3.6'

services:
  consul-server-1:
    image: consul:1.9.4
    container_name: consul-server-1
    restart: always
    network_mode: host
    # 以服务端模式启动
    command: agent -server -client=0.0.0.0 -node=consul-server-1 -bind={{ consul_server_1 }} -datacenter=dc01 -bootstrap-expect=3