# 校验节点软件系统及硬件系统、安装必要基础组件、docker
- hosts:
    - all
  gather_facts: false
  tasks:
    - name: "设置代理服务器环境变量"
      set_fact:
        proxy_env:
          http_proxy: "{{ http_proxy | default ('') }}"
          HTTP_PROXY: "{{ http_proxy | default ('') }}"
          https_proxy: "{{ https_proxy | default ('') }}"
          HTTPS_PROXY: "{{ https_proxy | default ('') }}"
          no_proxy: "{{ no_proxy | default ('') }}"
          NO_PROXY: "{{ no_proxy | default ('') }}"
      no_log: true

- name: 基础环境准备
  hosts:
    - all
  roles:
    - prepare/base
    - prepare/docker
  environment: "{{ proxy_env }}"

- name: 安装 consul
  hosts:
    - consul
  roles:
    - role: consul

- name: configure the master redis server
  hosts: redis-master
  # vars:
  #   - redis_password: "{{ redis_password }}"
  roles:
    - redis

- name: configure redis slaves
  hosts: redis-slave
  vars:
    - redis_slaveof: "{{ redis_master_ip }} {{ redis_port }}"
  roles:
    - redis

- name: configure redis sentinel nodes
  hosts: redis-sentinel
  vars:
    - redis_sentinel: true
    - redis_sentinel_monitors:
        - name: master01
          host: "{{ redis_master_ip }}"
          port: 6379
          auth_pass: "{{ redis_password }}"
  roles:
    - redis
# # 安装 etcd，并分发etcd证书到master节点
# - hosts:
#   - etcd
#   - new-etcd
#   - kube-master
#   - new-master
#   roles:
#   - etcd/certificates
#   - etcd/install

# # 生成 kubernetes 所需证书证书
# - hosts:
#   - kube-master
#   - new-master
#   - kube-worker
#   - new-worker
#   roles:
#   - kube-certificates

# # 初始化master节点
# - hosts:
#   - kube-master
#   - new-master
#   roles:
#   - kube-master

# # 初始化worker节点
# - hosts:
#   - kube-worker
#   - new-worker
#   roles:
#   - kube-worker

# # 标记各节点角色
# - hosts:
#   - kube-master
#   - kube-worker
#   - new-master
#   - new-worker
#   roles:
#   - post

# # 安装基础插件
# - hosts:
#   - kube-master[0]
#   roles:
#   - plugins/network-plugins
#   - plugins/ingress-controller
#   - plugins/metrics-server
#   - plugins/kubernetes-dashboard
#   - plugins/cert-manager
