---
# defaults file for docker
# 提权操作
ansible_become: true
# 集群pod ip段
kube_pod_subnet: 10.244.0.0/18
# 集群service ip段
kube_service_subnet: 10.244.64.0/18

_host_architecture_groups:
  x86_64: amd64
  aarch64: arm64
  armv7l: arm
host_architecture: >-
  {%- if ansible_architecture in _host_architecture_groups -%}
  {{ _host_architecture_groups[ansible_architecture] }}
  {%- else -%}
  {{ ansible_architecture }}
  {%- endif -%}

_host_distribution_groups:
  uos: debian
host_distribution: >-
  {%- if ansible_distribution in _host_distribution_groups -%}
  {{ _host_distribution_groups[ansible_distribution] }}
  {%- else -%}
  {{ ansible_distribution }}
  {%- endif -%}

host_distribution_release: >-
  {%- if (ansible_distribution_release == 'n/a') or (ansible_distribution_release is not defined) or (ansible_distribution_release == '') -%}
  buster
  {%- else -%}
  {{ ansible_distribution_release }}
  {%- endif -%}

# Docker版本
# yum list docker-ce --showduplicates --enablerepo=docker-ce | sort -r
docker_version: 20.10.5
containerd_version: 1.4.4
# containerd_version: 1.4.4-3
# CentOS
docker_yum_repo: https://mirrors.cloud.tencent.com/docker-ce/linux/centos/{{ ansible_distribution_major_version }}/$basearch/stable

# 国内镜像加速
docker_mirror:
# - "https://reg-mirror.qiniu.com"
# - "https://hub-mirror.c.163.com"
# - "https://docker.mirrors.ustc.edu.cn"

# 信任的不安全镜像库地址，默认为 Pod 和 Service 网段
docker_insecure_registries:
# - "{{ kube_pod_subnet }}"
# - "{{ kube_service_subnet }}"

# docker日志相关
docker_log_driver: "json-file"
docker_log_level: "warn"
docker_log_max_size: "10m"
docker_log_max_file: 3

# docker容器存储目录
docker_storage_dir: "/var/lib/docker"

# 并行镜像下载数量
docker_max_concurrent_downloads: 10

# container 运行时类型
container_manager: docker

# docker-compose 版本
docker_compose_version: 1.28.5
docker_compose_path: /usr/local/bin/docker-compose
