- name: 添加 Docker yum 仓库
  template:
    src: docker-ce.repo.j2
    dest: /etc/yum.repos.d/docker-ce.repo

- name: 安装 Docker
  yum:
    name:
      - "docker-ce-{{ docker_version }}.ce"
    state: present
    enablerepo: docker-ce-stable
  when: docker_version is version('18.09', '<')

- name: 安装 Docker
  yum:
    name:
      - "docker-ce-{{ docker_version }}"
      - "docker-ce-cli-{{ docker_version }}"
      - "containerd.io-{{ containerd_version }}"
      # - "containerd.io-{{ containerd_version.split('-')[0] }}"
    state: present
    enablerepo: docker-ce-stable
  when: docker_version is version('18.09', '>=')
