---
# tasks file for docker
- name: 判断 Docker 是否早已安装
  shell: >
    systemctl status docker | grep running || echo "not running"
  register: docker_already_running

- include_tasks: docker.yml
  when: '"active" in docker_already_running.stdout'

- include_tasks: docker.yml
  when:
  - container_manager == "docker"
  - '"active" not in docker_already_running.stdout'
