# 软件资源校验
- name: 校验节点操作系统
  assert:
    that: ansible_distribution in [ 'CentOS' ]
    msg: "节点：{{ inventory_hostname }} {{ ansible_distribution }}操作系统暂不支持本脚本。"

- name: 校验节点 systemd 类型操作系统
  assert:
    that: ansible_service_mgr == "systemd"
    msg: "节点：{{ inventory_hostname }} 期望为systemd类型操作系统，实际获取：{{ ansible_service_mgr }}，安装需求校验不通过。"

- name: 校验节点系统内核
  assert:
    that: ansible_kernel is version('3.10', '>=')
    msg: "节点：{{ inventory_hostname }} 系统内核版本小于3.10，实际获取：{{ ansible_kernel }}，安装需求校验不通过。"

- name: 校验节点系统架构
  assert:
    that: ansible_machine in [ 'x86_64','aarch64' ]
    msg: "节点：{{ inventory_hostname }} {{ ansible_machine }} 系统指令集不支持本脚本安装Kubernetes集群"

- name: 校验节点系统版本
  assert:
    that: ansible_distribution_version is version('7.4', '>=')
    msg: "节点：{{ inventory_hostname }} 系统版本期望不小于CentOS 7.4，实际获取：{{ ansible_distribution_version }}，安装需求校验不通过。"
  when:
    - ansible_distribution == "CentOS"

# 物理资源校验
- name: 校验节点内存
  assert:
    that: ansible_memtotal_mb >= 2*1024*0.85
    msg: "节点：{{ inventory_hostname }} 内存期望不小于2G，实际获取：{{ ansible_memtotal_mb }}MB，安装需求校验不通过。"
  when:
    - inventory_hostname in groups['all']

- name: 校验节点CPU核数
  assert:
    that: ansible_processor_vcpus >= 2
    msg: "节点：{{ inventory_hostname }} CPU核数期望不小于2C，实际获取：{{ ansible_memtotal_mb }}C，安装需求校验不通过。"
  when:
    - inventory_hostname in groups['all]
